# MyReports analysis endpoints (Ledger/Receivable-Payable/Stock/Hire/Production/Misc) — port-break sweep.
$fd='01-01-2010'; $td='31-12-2026'
Probe 'getPRInvoiceWise'        'MyReports/getPRInvoiceWise'        @{item='0';supplier='0';fromdate=$fd;to=$td;ddmc='0'}
Probe 'getSRInvoiceWise'        'MyReports/getSRInvoiceWise'        @{item='0';customer='0';category='0';fromdate=$fd;to=$td;ddmc='0'}
Probe 'GetLedger2'              'MyReports/GetLedger2'              @{AccId='1';fromdate=$fd;todate=$td;AccGroup='0';pdc='false'}
Probe 'GetLedger'               'MyReports/GetLedger'               @{AccId='1';fromdate=$fd;todate=$td;AccGroup='0';pdc='false'}
Probe 'GetLedgertax'            'MyReports/GetLedgertax'            @{AccId='1';fromdate=$fd;todate=$td;AccGroup='0';pdc='false'}
Probe 'GetLedgermin'            'MyReports/GetLedgermin'            @{AccId='1';fromdate=$fd;todate=$td;AccGroup='0';pdc='false'}
Probe 'GetLedgerProp'           'MyReports/GetLedgerProp'           @{AccId='1';fromdate=$fd;todate=$td;AccGroup='0';pdc='false'}
Probe 'getsaleledgers'          'MyReports/getsaleledgers'          @{Cuss='1';From=$fd;To=$td}
Probe 'GetReceivable'           'MyReports/GetReceivable'           @{CSType='';Sups='0';Cuss='0';fromdate=$fd;todate=$td;agedays='0';TTtype='0';empp='0';empp2='0'}
Probe 'GetReceivableLedger'     'MyReports/GetReceivableLedger'     @{CSType='';Sups='0';Cuss='0';fromdate=$fd;todate=$td;agedays='0';AgeDaystwo='0';TTtype='0';empp='0'}
Probe 'GetReceivableLedgerremove' 'MyReports/GetReceivableLedgerremove' @{CSType='';Sups='0';Cuss='0';fromdate=$fd;todate=$td;agedays='0';AgeDaystwo='0';TTtype='0';empp='0'}
Probe 'GetPayable'              'MyReports/GetPayable'              @{CSType='';Sups='0';Cuss='0';fromdate=$fd;todate=$td;agedays='0';TTtype='0'}
Probe 'GetPayableclear'         'MyReports/GetPayableclear'         @{CSType='';Sups='0';Cuss='0';fromdate=$fd;todate=$td;agedays='0';TTtype='0'}
Probe 'GetStockAdjustmentReport' 'MyReports/GetStockAdjustmentReport' @{Voucher='';Item='0';fromdate=$fd;todate=$td}
Probe 'GetStockAdjItemWiseReport' 'MyReports/GetStockAdjItemWiseReport' @{Item='0';fromdate=$fd;todate=$td}
Probe 'GetMaterialFromParty'    'MyReports/GetMaterialFromParty'    @{Voucher='';Party='0';fromdate=$fd;todate=$td;MC='0'}
Probe 'GetMaterialToParty'      'MyReports/GetMaterialToParty'      @{Voucher='';Party='0';fromdate=$fd;todate=$td;MC='0'}
Probe 'GetStockTransferReport'  'MyReports/GetStockTransferReport'  @{Voucher='';MCFrom='0';MCTo='0';fromdate=$fd;todate=$td}
Probe 'GetHireReturn'           'MyReports/GetHireReturn'           @{BillNo='';customer='0';fromdate=$fd;todate=$td;ddlMC='0';project='0';task='0'}
Probe 'GetHireExpire'           'MyReports/GetHireExpire'           @{BillNo='';customer='0';fromdate=$fd;todate=$td;Htype='0'}
Probe 'GetCrossHireExpire'      'MyReports/GetCrossHireExpire'      @{BillNo='';supplier='0';fromdate=$fd;todate=$td;Htype='0'}
Probe 'GetPurchaseUsage'        'MyReports/GetPurchaseUsage'        @{srchtxt='';Item='0';supplier='0';ItemBrand='0';ItemCategory='0';saleExe='0';matReqBy='0';fromdate=$fd;todate=$td;mc='0'}
Probe 'GetPurchaseUsageDetails' 'MyReports/GetPurchaseUsageDetails' @{Item='0';fromdate=$fd;todate=$td}
Probe 'GetAmountReceivablePayable2' 'MyReports/GetAmountReceivablePayable2' @{ddlType='0';pdc='false';fromdate=$fd;todate=$td}
Probe 'GetAmountReceivablePayable3' 'MyReports/GetAmountReceivablePayable3' @{ddlType='0';pdc='false';emp='0'}
Probe 'GetAmountReceivablePayable'  'MyReports/GetAmountReceivablePayable'  @{nextdate=$td;ddlType='0';pdc='false';emp='0';ondate=$td;exp='0'}
Probe 'GetAmountReceivablePayableage' 'MyReports/GetAmountReceivablePayableage' @{nextdate=$td;ddlType='0';pdc='false';emp='0';ondate=$td;exp='0'}
Probe 'GetAmountReceivablePayablessalesman' 'MyReports/GetAmountReceivablePayablessalesman' @{nextdate=$td;ddlType='0';pdc='false';emp='0';ondate=$td;exp='0'}
Probe 'GetContactDetails'       'MyReports/GetContactDetails'       @{CustomerId='1'}
Probe 'GetAllRemarks'           'MyReports/GetAllRemarks'           @{CustomerId='1'}
Probe 'GetAllRemarksaccount'    'MyReports/GetAllRemarksaccount'    @{CustomerId='1'}
Probe 'GetTerms'                'MyReports/GetTerms'                @{CustomerId='1'}
Probe 'getUnPaidInvoices'       'MyReports/getUnPaidInvoices'       @{particular='0'}
Probe 'GetHireNotification'     'MyReports/GetHireNotification'     @{BillNo='';customer='0';fromdate=$fd;todate=$td;Htype='0'}
Probe 'GetPOrderOutstanding'    'MyReports/GetPOrderOutstanding'    @{item='0';supp='0';fromdate=$fd;todate=$td}
Probe 'GetSOrderOutstanding'    'MyReports/GetSOrderOutstanding'    @{item='0';cust='0';fromdate=$fd;todate=$td}
Probe 'GetProduction'           'MyReports/GetProduction'           @{vno='';mc='0';branch='0';fromdate=$fd;todate=$td;project='0';task='0'}
Probe 'GetProductionSummary'    'MyReports/GetProductionSummary'    @{BOM='0';generated='0';fromdate=$fd;todate=$td;mc='0'}
Probe 'GetUnassemble'           'MyReports/GetUnassemble'           @{vno='';mc='0';branch='0';fromdate=$fd;todate=$td;project='0';task='0'}
Probe 'GetPurchaseView'         'MyReports/GetPurchaseView'         @{customer='0';fromdate=$fd;todate=$td;pdc='false'}
Probe 'GetIncomeView'           'MyReports/GetIncomeView'           @{customer='0';fromdate=$fd;todate=$td;pdc='false'}
Probe 'GetExpenseView'          'MyReports/GetExpenseView'          @{customer='0';fromdate=$fd;todate=$td;pdc='false'}
Probe 'GetSimplePL'             'MyReports/GetSimplePL'             @{fromdate=$fd;todate=$td}
Probe 'GetApproval'             'MyReports/GetApproval'             @{FromDate=$fd;ToDate=$td;invoice='';type='';appstat='0';sortfive='false'}
Probe 'GetReminder'             'MyReports/GetReminder'             @{status='';type='';fromdate=$fd;todate=$td}
Probe 'GetPDC'                  'MyReports/GetPDC'                  @{bank='0';vtype='';pdcstat='';fromdate=$fd;todate=$td}
Probe 'GetAssignedTask'         'MyReports/GetAssignedTask'         @{emp='0';fromdate=$fd;todate=$td}
Probe 'GetItemDetails'          'MyReports/GetItemDetails'          @{Item='2';ExpiryDate=''}
Probe 'GetEmployeeDetails'      'MyReports/GetEmployeeDetails'      @{Type='';EmployeeId='0';From=$fd;CutOff='0'}
