# SalesReport data endpoints — full port-break sweep. Params match each action signature.
# Full history range; nullable ids use '0' (the codebase's "All" sentinel), bools 'false'.
$fd='01-01-2010'; $td='31-12-2026'
Probe 'GetAllSaleprofitdepartment'      'SalesReport/GetAllSaleprofitdepartment'      @{seno='';paymethod='0';customer='0';SalesExecutive='';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0'}
Probe 'GetAllSaleemployee'              'SalesReport/GetAllSaleemployee'              @{seno='';paymethod='0';customer='0';SalesExecutive='0';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';perwise='false'}
Probe 'GetAllSal'                       'SalesReport/GetAllSal'                       @{srchtxt='';customer='0';fromdate=$fd;todate=$td;comparprices='0';brand='0';category='0'}
Probe 'GetAllSaleRebate'                'SalesReport/GetAllSaleRebate'                @{srchtxt='';brand='0';category='0';item='0';seno='';paymethod='0';customer='0';SalesExecutive='0';SalesMan='0';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0'}
Probe 'GetComparison'                   'SalesReport/GetComparison'                   @{srchtxt='';brand='0';category='0';item='0';ddMCfrom='0';ddMCto='0'}
Probe 'GetAllSale'                      'SalesReport/GetAllSale'                      @{srchtxt='';brand='0';category='0';item='0';seno='';paymethod='0';customer='0';SalesExecutive='0';SalesMan='0';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0'}
Probe 'GetAllSaleRebateCustomerWise'    'SalesReport/GetAllSaleRebateCustomerWise'    @{srchtxt='';brand='0';category='0';item='0';seno='';paymethod='0';customer='0';SalesExecutive='0';SalesMan='0';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';custyp='0'}
Probe 'GetAllSaleRebateCustomerWisebonus' 'SalesReport/GetAllSaleRebateCustomerWisebonus' @{srchtxt='';brand='0';category='0';item='0';seno='';paymethod='0';customer='0';SalesExecutive='0';SalesMan='0';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';custyp='0'}
Probe 'GetAllSaleReturn'                'SalesReport/GetAllSaleReturn'                @{seno='';paymethod='0';customer='0';SalesExecutive='0';SalesMan='0';fromdate=$fd;todate=$td;type='0';ddMC='0';project='0';task='0'}
Probe 'GetAllSaleprofitnew'             'SalesReport/GetAllSaleprofitnew'             @{seno='';perhourcost='0';paymethod='0';SalesMan='0';customer='0';SalesExecutive='0';fromdate=$fd;todates=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';srchtxt='';employeehourrate='false';source='0';location='';technician='0'}
Probe 'GetAllSaleprofitgroup'           'SalesReport/GetAllSaleprofitgroup'           @{completed='';seno='';perhourcost='0';paymethod='0';SalesMan='0';customer='0';SalesExecutive='0';fromdate=$fd;todates=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';srchtxt='';employeehourrate='false';source='0';location='';technician='0';sourcelead='0';cached='false';cusage='0';nostocktransfer='false'}
Probe 'GetAllSaleprofitsummery'         'SalesReport/GetAllSaleprofitsummery'         @{completed='';seno='';perhourcost='0';paymethod='0';SalesMan='0';customer='0';SalesExecutive='0';fromdate=$fd;todates=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';srchtxt='';employeehourrate='false';amccus='false';source='0';location='';technician='0';sourcelead='0';cached='false';cusage='0';nostocktransfer='false'}
Probe 'GetAllSaleprofit'                'SalesReport/GetAllSaleprofit'                @{completed='';seno='';perhourcost='0';paymethod='0';SalesMan='0';customer='0';SalesExecutive='0';fromdate=$fd;todates=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0';srchtxt='';employeehourrate='false';source='0';location='';technician='0';sourcelead='0';cached='false';cusage='0';nostocktransfer='false'}
Probe 'GetAllSaleprofitCASA'            'SalesReport/GetAllSaleprofitCASA'            @{seno='';paymethod='0';customer='0';SalesExecutive='0';fromdate=$fd;todate=$td;type='0';ddMC='0';satype='';htype='0';hfdate='';htdate='';project='0';task='0'}
Probe 'GetCustomerWise'                 'SalesReport/GetCustomerWise'                 @{customer='0';fromdate=$fd;todate=$td;Salety='';ddMC='0';project='0';task='0'}
Probe 'MonthWise'                       'SalesReport/MonthWise'                       @{Year='2024'}
Probe 'GetItemWise'                     'SalesReport/GetItemWise'                     @{item='';fromdate=$fd;todate=$td;ddMC='0';Salety='';Brand='0';SalesExecutive='0';Category='0';Salesman='0';supplier='0'}
Probe 'GetItemWisenew'                  'SalesReport/GetItemWisenew'                  @{item='';fromdate=$fd;todate=$td;ddMC='0';Salety='';Brand='0';SalesExecutive='0';Category='0';Salesman='0'}
Probe 'GetCategoryWise'                 'SalesReport/GetCategoryWise'                 @{category='0';fromdate=$fd;todate=$td;ddMC='0';Salety=''}
Probe 'GetBrandWise'                    'SalesReport/GetBrandWise'                    @{brand='0';fromdate=$fd;todate=$td;Salety='';ddmc='0'}
Probe 'GetSalesExeWise'                 'SalesReport/GetSalesExeWise'                 @{salesexec='0';fromdate=$fd;todate=$td;Salety='';ddmc='0'}
Probe 'GetSalessummary'                 'SalesReport/GetSalessummary'                 @{salesexec='0';fromdate=$fd;todate=$td;Salety='';ddmc='0'}
Probe 'GetCommission'                   'SalesReport/GetCommission'                   @{brand='0';fromdate=$fd;todate=$td;Salety='';ddmc='0'}
Probe 'GetSalesCommission'              'SalesReport/GetSalesCommission'              @{ddlemp='0';fromdate=$fd;todate=$td}
Probe 'GetCustomer'                     'SalesReport/GetCustomer'                     @{FromDate=$fd;ToDate=$td}
Probe 'GetCustomerItemWise'             'SalesReport/GetCustomerItemWise'             @{ddlCustomer='0';ddlItem='0';From=$fd;To=$td;SalType='';ddmc='0'}
Probe 'GetMonthlySale'                  'SalesReport/GetMonthlySale'                  @{fromdate=$fd;todate=$td;ddmc='0'}
Probe 'GetDayWise'                      'SalesReport/GetDayWise'                      @{From=$fd;To=$td;ddmc='0';emp='0';task='0';project='0';customer='0';hfrom='';hto='';htype='0';stype=''}
Probe 'GetCashOrCredit'                 'SalesReport/GetCashOrCredit'                 @{From=$fd;To=$td;ddmc='0'}
Probe 'GetSupplierWise'                 'SalesReport/GetSupplierWise'                 @{supplier='0';fromdate=$fd;todate=$td;ddmc='0'}
Probe 'GetCustomerAreaWise'             'SalesReport/GetCustomerAreaWise'             @{state='';ddmc='0'}
Probe 'GetSaleReceiptSummary'           'SalesReport/GetSaleReceiptSummary'           @{vno='';customer='0';fromdate=$fd;todate=$td}
Probe 'GetCustomerItemWiseSum'          'SalesReport/GetCustomerItemWiseSum'          @{Cust='0';Item='0';fromdate=$fd;todate=$td;MC='0'}
Probe 'getitemDetails'                  'SalesReport/getitemDetails'                  @{item='0';customer='0';fromdate=$fd;to=$td;ddmc='0'}
Probe 'getcustDetails'                  'SalesReport/getcustDetails'                  @{cust='0';fromdate=$fd;to=$td;ddmc='0'}
Probe 'getInvoiceWise'                  'SalesReport/getInvoiceWise'                  @{item='0';customer='0';fromdate=$fd;todate=$td;ddmc='0'}
