Probe 'Contact-getContact' 'Contact/getContact' @{Name='';Email='';Phone='';Mobile='';Group=''}
Probe 'Contact-GroupGetData' 'Contact/GroupGetData' @{}
Probe 'ContactType-GetContactType' 'ContactType/GetContactType' @{ColName=''}
Probe 'CustomerType-GetCustomerType' 'CustomerType/GetCustomerType' @{ColName=''}
Probe 'ServiceType-GetDetails' 'ServiceType/GetDetails' @{AmcId='0';PDate=''}
Probe 'Checklist-GetCheck' 'Checklist/GetCheck' @{Stage='0'}
Probe 'TaskGroup-GetTaskTypewithstatus' 'TaskGroup/GetTaskTypewithstatus' @{}
Probe 'AMCContractName-GetContractName' 'AMCContractName/GetContractName' @{ColName=''}
Probe 'AMCContractType-GetContractType' 'AMCContractType/GetContractType' @{ColName=''}
Probe 'AMCStatus-GetAmcStatus' 'AMCStatus/GetAmcStatus' @{}
Probe 'CustRelation-GetSalesEntry' 'CustomerRelation/GetSalesEntry' @{}
Probe 'CustRelation-GetSalesOrder' 'CustomerRelation/GetSalesOrder' @{}
Probe 'CustRelation-GetQuotEntry' 'CustomerRelation/GetQuotEntry' @{}
Probe 'CustRelation-GetHireExp' 'CustomerRelation/GetHireExp' @{}
Probe 'CustRelation-GetCrossHireExp' 'CustomerRelation/GetCrossHireExp' @{}
