Probe 'PT-Getmanhour-1'     'ProTask/Getmanhour'         @{protaskid='1';stDate=''}
Probe 'PT-Getmanhour-50'    'ProTask/Getmanhour'         @{protaskid='50';stDate=''}
Probe 'PT-Getmanhour-100'   'ProTask/Getmanhour'         @{protaskid='100';stDate=''}
Probe 'PT-Getmanhour-200'   'ProTask/Getmanhour'         @{protaskid='200';stDate=''}
Probe 'PT-Getmanhour-500'   'ProTask/Getmanhour'         @{protaskid='500';stDate=''}
Probe 'PT-Getmanhour-1000'  'ProTask/Getmanhour'         @{protaskid='1000';stDate=''}
Probe 'PTNT-Getmanhour-50'  'ProTaskNonTech/Getmanhour'  @{protaskid='50';stDate=''}
Probe 'PTNT-Getmanhour-200' 'ProTaskNonTech/Getmanhour'  @{protaskid='200';stDate=''}
Probe 'PTNT-Getmanhour-500' 'ProTaskNonTech/Getmanhour'  @{protaskid='500';stDate=''}
